FROM ubuntu
MAINTAINER frundh

ENV SDK_DOCTOR_VERSION '1.0.1'

ENV CWD_DIR /cwd/

RUN echo '# Download SDK-Doctor'
ADD https://github.com/couchbaselabs/sdk-doctor/releases/download/v${SDK_DOCTOR_VERSION}/sdk-doctor-linux /bin/
RUN mv /bin/sdk-doctor-linux /bin/sdk-doctor
RUN chmod +x /bin/sdk-doctor

WORKDIR ${CWD_DIR}